### ISSUE TITLE
No tensorflow reported when trying to run nvidia image for sagemaker

### ISSUE THREAD

**Issue by breadcentric** [aws-deepracer-community/deepracer-core#18]
Steps to reproduce:
I followed instructions in the readme, but instead of `docker pull nabcrr/sagemaker-rl-tensorflow:console` I did `docker pull nabcrr/sagemaker-rl-tensorflow:nvidia` and then tagged it as instructed. Before running `(cd rl_coach; ipython rl_deepracer_coach_robomaker.py)` I went to that file and commented out the line that Lonon mentioned in #17 

Expected result:
When running `(cd rl_coach; ipython rl_deepracer_coach_robomaker.py)` my gpu is detected and training begins

Actual result:
```
algo-1-vrm2i_1  | ERROR: ld.so: object '/libchangehostname.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
algo-1-vrm2i_1  | Reporting training FAILURE
algo-1-vrm2i_1  | framework error:
algo-1-vrm2i_1  | Traceback (most recent call last):
algo-1-vrm2i_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_trainer.py", line 60, in train
algo-1-vrm2i_1  |     framework = importlib.import_module(framework_name)
algo-1-vrm2i_1  |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
algo-1-vrm2i_1  |     return _bootstrap._gcd_import(name[level:], package, level)
algo-1-vrm2i_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
algo-1-vrm2i_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
algo-1-vrm2i_1  |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
algo-1-vrm2i_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
algo-1-vrm2i_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
algo-1-vrm2i_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
algo-1-vrm2i_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/training.py", line 24, in <module>
algo-1-vrm2i_1  |     import tensorflow as tf
algo-1-vrm2i_1  | ModuleNotFoundError: No module named 'tensorflow'
algo-1-vrm2i_1  |
algo-1-vrm2i_1  | No module named 'tensorflow'
```

System info:
Ubuntu 18.04.2 LTS

```
$ docker run --runtime=nvidia --rm nvidia/cuda:10.1-base nvidia-smi
Mon Jun 17 22:24:56 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 660M    Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   46C    P8    N/A /  N/A |    266MiB /  1999MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
```

**Comment by breadcentric** [comment]
Note: adding tensorflow-gpu==1.11.0 and rebuilding the image solves the issue

**Comment by crr0004** [comment]
Image has been updated for this
