### ISSUE TITLE
Updated sagemaker nvidia image does not work

### ISSUE THREAD

**Issue by jarrettj** [aws-deepracer-community/deepracer-core#74]
Hi,

Good day.

Running the sagemaker-rl-tensorflow:nvidia_v1.1 tag gives the following error:

```
algo-1-n8fui_1  | Reporting training FAILURE
algo-1-n8fui_1  | framework error: 
algo-1-n8fui_1  | Traceback (most recent call last):
algo-1-n8fui_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_trainer.py", line 60, in train
algo-1-n8fui_1  |     framework = importlib.import_module(framework_name)
algo-1-n8fui_1  |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
algo-1-n8fui_1  |     return _bootstrap._gcd_import(name[level:], package, level)
algo-1-n8fui_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
algo-1-n8fui_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
algo-1-n8fui_1  |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
algo-1-n8fui_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
algo-1-n8fui_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
algo-1-n8fui_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
algo-1-n8fui_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow_container/training.py", line 24, in <module>
algo-1-n8fui_1  |     import tensorflow as tf
algo-1-n8fui_1  | ModuleNotFoundError: No module named 'tensorflow'
algo-1-n8fui_1  | 
algo-1-n8fui_1  | No module named 'tensorflow'
```

Regards

**Comment by breadcentric** [comment]
We've moved on to using https://github.com/aws-deepracer-community/deepracer-for-cloud for running deepracer in local env

Closing
